# Generated by Django 4.2.4 on 2025-03-21 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pwd_records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disability_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PWDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6)),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to=pwd_records.models.upload_image_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('disability_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwd_records.disabilitytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('approval_date', models.DateField()),
                ('pwd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwd_records.pwdrecord')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwd_records.servicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_checkup_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pwd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwd_records.pwdrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('under review', 'Under Review'), ('resolved', 'Resolved')], default='new', max_length=12)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('pwd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwd_records.pwdrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_certificate', models.ImageField(blank=True, null=True, upload_to=pwd_records.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pwd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwd_records.pwdrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
