# Generated by Django 4.2.4 on 2025-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('id_card', 'ID Card')], max_length=50)),
                ('related_id', models.PositiveIntegerField()),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
