# Generated by Django 4.2.4 on 2025-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd_records', '0002_documentauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportservices',
            name='support_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pwdrecord',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
    ]
