# Generated by Django 4.2.4 on 2025-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd_records', '0003_supportservices_support_name_alter_pwdrecord_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwdrecord',
            name='area_council',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pwdrecord',
            name='community',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pwdrecord',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
