# Generated by Django 4.2.4 on 2026-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwd_records', '0004_pwdrecord_area_council_pwdrecord_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwdrecord',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
