# Generated by Django 4.2.4 on 2025-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('social_worker', 'Social Worker'), ('medical_officer', 'Medical Officer')], default='social_worker', max_length=20),
        ),
    ]
